#!/usr/bin/env sh

# This loads nvm.sh and sets the correct PATH before running hook
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

. "$(dirname -- "$0")/_/husky.sh"

npx git-format-staged -f 'prettier --ignore-unknown --stdin --stdin-filepath "{}"' .
npm run typecheck
